#pragma once
//フォントの太さ
enum FONT_WEIGHT
{
	FONT_WEIGHT_THIN = 100,
	FONT_WEIGHT_EXTRA_LIGHT = 200,
	FONT_WEIGHT_ULTRA_LIGHT = 200,
	FONT_WEIGHT_LIGHT = 300,
	FONT_WEIGHT_SEMI_LIGHT = 350,
	FONT_WEIGHT_NORMAL = 400,
	FONT_WEIGHT_REGULAR = 400,
	FONT_WEIGHT_MEDIUM = 500,
	FONT_WEIGHT_DEMI_BOLD = 600,
	FONT_WEIGHT_SEMI_BOLD = 600,
	FONT_WEIGHT_BOLD = 700,
	FONT_WEIGHT_EXTRA_BOLD = 800,
	FONT_WEIGHT_ULTRA_BOLD = 800,
	FONT_WEIGHT_BLACK = 900,
	FONT_WEIGHT_HEAVY = 900,
	FONT_WEIGHT_EXTRA_BLACK = 950,
	FONT_WEIGHT_ULTRA_BLACK = 950
};

//フォントのスタイル(斜体等)
enum FONT_STYLE
{
	FONT_STYLE_NORMAL,	//通常
	FONT_STYLE_OBLIQUE,	//斜体1
	FONT_STYLE_ITALIC	//斜体2
};